### ISSUE TITLE
Code Review for "PecanPy: a fast, efficient, and parallelized Python implementation of node2vec"

### ISSUE THREAD

**Issue by cthoyt** [krishnanlab/PecanPy#12]
Dear @RemyLau and @arjunkrish,

I've been invited to review your manuscript. I'm sure this was no coincidence, as I'm always trolling bioRxiv for interesting software papers and making PRs :) Overall, I'm quite happy with the way you wrote the manuscript, especially how you structured the dichotomy between the main manuscript and supplement. I will give specific comments for the paper itself in the review you will receive directly from the journal.

You'll also see I've left quite a few issues on this repository ranging from specific code suggestions to more philosophical discussions. I've meant all in good faith - have no doubt that your paper will be accepted. However, I'm likely one of the pickiest code reviewers in the entire bioinformatics community, so we're going to make your repository the best it can possibly be before the review is done. I hope you're excited about the idea, since you're already 90% of the way there. Most methods published in the literature are utterly useless, so I already really appreciate the work you've done and how you've done it until now.

Greetings from Bonn, Germany. Have a nice weekend.

-Charlie Hoyt

Related issues:
- [x] #4 Archive repository on Zenodo
- [ ] #5 Add progress monitoring (if possible)
- [x] #6 Fix logging time widths
- [x] #7 Improve understandability of alias_draw() function
- [x] #8 Enforce consistent code style
- [x] #9 Deploy to PyPI
- [x] #10 Give feedback on potentially bad choices of settings
- [x] #11 Enable reproduction of results of manuscript
- [x] #13 Improve documentation and build with Sphinx
- [x] #15 Host documentation with ReadTheDocs

**Comment by RemyLau** [comment]
@cthoyt Thank you so much for the clear instructions!

**Comment by arjunkrish** [comment]
Hey @cthoyt,
Thanks a lot for your thorough and helpful code review of our software!

We really appreciate the effort you have put in towards helping make the software better. We are definitely excited about working on resolving the issues you've posted. Thanks for the clear instructions accompanying each one of them. @RemyLau will post comments as and when he gets to them.

Cheers!
Arjun

**Comment by cthoyt** [comment]
I'd go as far as to call this issue closed - I've just submitted a new review with a suggestion to accept without further revisions ;)

(however, there's always room for improvement of documentation for *any* package)
